import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const directory = path.dirname(fileURLToPath(import.meta.url));
const mappings = [];
const cases = [];
const combiningMarks = [];
const mark = /\p{M}/u;

for (let codePoint = 0; codePoint <= 0x10ffff; codePoint += 1) {
  if (codePoint >= 0xd800 && codePoint <= 0xdfff) continue;
  const input = String.fromCodePoint(codePoint);
  const output = input.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  if (output === input) continue;
  mappings.push({ codePoint, output });
  cases.push({ input, output });
}

for (let codePoint = 0; codePoint <= 0x10ffff; codePoint += 1) {
  if (codePoint >= 0xd800 && codePoint <= 0xdfff) continue;
  const input = String.fromCodePoint(codePoint);
  if (!mark.test(input) || input.normalize('NFD') !== input) continue;
  const probe = `a\u0300${input}\u0334`;
  if (probe.normalize('NFD') === probe) continue;
  combiningMarks.push(codePoint);
}

const combiningClassOrder = (left, right) => {
  const leftMark = String.fromCodePoint(left);
  const rightMark = String.fromCodePoint(right);
  const forward = `a${leftMark}${rightMark}`.normalize('NFD');
  const leftFirst = forward.indexOf(leftMark) < forward.indexOf(rightMark);
  const reverse = `a${rightMark}${leftMark}`.normalize('NFD');
  const leftFirstReverse = reverse.indexOf(leftMark) < reverse.indexOf(rightMark);
  if (leftFirst && leftFirstReverse) return -1;
  if (!leftFirst && !leftFirstReverse) return 1;
  return 0;
};
combiningMarks.sort(combiningClassOrder);
const combiningClasses = [];
let combiningClass = 0;
for (let i = 0; i < combiningMarks.length; i += 1) {
  if (i > 0 && combiningClassOrder(combiningMarks[i - 1], combiningMarks[i]) !== 0) combiningClass += 1;
  combiningClasses.push({ codePoint: combiningMarks[i], combiningClass });
}

for (const input of ['# Gōal', '# Šcope', 'macron-goal', 'caron-scope', 'İ', 'ſ', 'K']) {
  cases.push({ input, output: input.normalize('NFD').replace(/[\u0300-\u036f]/g, '') });
}

const entries = mappings.map(({ codePoint, output }) => {
  const key = codePoint <= 0xffff
    ? `\\u${codePoint.toString(16).padStart(4, '0')}`
    : `\\U${codePoint.toString(16).padStart(8, '0')}`;
  return `\t'${key}': ${JSON.stringify(output)},`;
});
const combiningEntries = combiningClasses.map(({ codePoint, combiningClass }) => {
  const key = codePoint <= 0xffff
    ? `\\u${codePoint.toString(16).padStart(4, '0')}`
    : `\\U${codePoint.toString(16).padStart(8, '0')}`;
  return `\t'${key}': ${combiningClass},`;
});
const table = [
  '// Code generated by node internal/text/testdata/gen_nfd.mjs; DO NOT EDIT.',
  'package text',
  '',
  'var nfdMappings = map[rune]string{',
  ...entries,
  '}',
  '',
  'var nfdCombiningClasses = map[rune]uint8{',
  ...combiningEntries,
  '}',
  '',
].join('\n');

const tablePath = path.resolve(directory, '..', 'nfd_table.go');
fs.writeFileSync(tablePath, table);
const formatted = spawnSync('gofmt', ['-w', tablePath], { encoding: 'utf8' });
if (formatted.error || formatted.status !== 0) {
  throw formatted.error ?? new Error(formatted.stderr || `gofmt exited ${formatted.status}`);
}
fs.writeFileSync(path.join(directory, 'nfd.json'), `${JSON.stringify(cases)}\n`);
process.stdout.write(`wrote ${mappings.length} NFD mappings, ${combiningEntries.length} combining classes, and ${cases.length} differential cases\n`);
